// Docs: https://www.instantdb.com/docs/modeling-data

import { i } from '@instantdb/react-native';

const _schema = i.schema({
  entities: {
    $files: i.entity({
      path: i.string().unique().indexed(),
      url: i.string(),
    }),
    $streams: i.entity({
      abortReason: i.string().optional(),
      clientId: i.string().unique().indexed(),
      done: i.boolean().optional(),
      size: i.number().optional(),
    }),
    $users: i.entity({
      display_name: i.string().optional(),
      email: i.string().unique().indexed().optional(),
      imageURL: i.string().optional(),
      type: i.string().optional(),
    }),
    account_deletion_requests: i.entity({
      apple_revocation_error: i.string().optional(),
      apple_revocation_status: i.string().indexed().optional(),
      auth_provider: i.string().indexed().optional(),
      auth_user_id: i.string().unique().indexed(),
      completed_at: i.date().indexed().optional(),
      created_at: i.date().indexed().optional(),
      email: i.string().indexed().optional(),
      processing_lock_id: i.string().optional(),
      profile_id: i.string().indexed().optional(),
      requested_at: i.date().indexed(),
      restored_at: i.date().indexed().optional(),
      scheduled_for_at: i.date().indexed(),
      status: i.string().indexed(),
      updated_at: i.date().indexed().optional(),
    }),
    booking_occasions: i.entity({
      created_at: i.date().indexed().optional(),
      is_active: i.boolean().indexed().optional(),
      label_key: i.string(),
      sort_order: i.number().indexed().optional(),
      value: i.string().unique().indexed(),
    }),
    booking_time_slots: i.entity({
      available: i.boolean().indexed(),
      created_at: i.date().indexed().optional(),
      sort_order: i.number().indexed().optional(),
      time: i.string().unique().indexed(),
    }),
    events: i.entity({
      attendees: i.number().optional(),
      badge: i.string().optional(),
      badge_color: i.string().optional(),
      category: i.string().indexed().optional(),
      created_at: i.date().indexed().optional(),
      date: i.string().indexed(),
      day_label: i.string().optional(),
      description: i.string().optional(),
      featured: i.boolean().indexed().optional(),
      guest_price: i.string().optional(),
      image: i.string(),
      location: i.string(),
      member_price: i.string().optional(),
      price: i.string(),
      time: i.string(),
      title: i.string(),
      vip_price: i.string().optional(),
    }),
    member_offers: i.entity({
      badge_key: i.string(),
      code: i.string().optional(),
      created_at: i.date().indexed().optional(),
      is_active: i.boolean().indexed().optional(),
      kind: i.string().indexed(),
      sort_order: i.number().indexed().optional(),
      subtitle_key: i.string(),
      terms_key: i.string().optional(),
      title_key: i.string(),
    }),
    menu_categories: i.entity({
      created_at: i.date().indexed().optional(),
      is_active: i.boolean().indexed().optional(),
      key: i.string().unique().indexed(),
      label_key: i.string(),
      sort_order: i.number().indexed().optional(),
    }),
    menu_items: i.entity({
      category_key: i.string().indexed(),
      created_at: i.date().indexed().optional(),
      description_key: i.string(),
      image: i.string(),
      is_active: i.boolean().indexed().optional(),
      name_key: i.string(),
      price: i.string(),
      sort_order: i.number().indexed().optional(),
      tag_key: i.string().optional(),
    }),
    news_items: i.entity({
      created_at: i.date().indexed().optional(),
      image: i.string().optional(),
      subtitle: i.string().optional(),
      time_label: i.string().optional(),
      title: i.string(),
    }),
    partner_redemptions: i.entity({
      created_at: i.date().indexed().optional(),
      entry_key: i.string().unique().indexed(),
      partner_code: i.string().optional(),
      partner_id: i.string().indexed(),
      redemption_method: i.string().indexed(),
      status: i.string().indexed(),
    }),
    partners: i.entity({
      category: i.string().indexed().optional(),
      code: i.string().optional(),
      created_at: i.date().indexed().optional(),
      description: i.string().optional(),
      discount_label: i.string().optional(),
      discount_percentage: i.number().optional(),
      image: i.string().optional(),
      name: i.string(),
    }),
    pos_bills: i.entity({
      amount_vnd: i.number().indexed(),
      canonical_bill_id: i.string().unique().indexed(),
      claimed_at: i.date().indexed().optional(),
      claimed_by_profile_id: i.string().indexed().optional(),
      claimed_reward_transaction_id: i.string().indexed().optional(),
      closed_at: i.date().indexed().optional(),
      created_at: i.date().indexed().optional(),
      currency: i.string().indexed(),
      entry_key: i.string().unique().indexed(),
      last_synced_at: i.date().indexed().optional(),
      paid_at: i.date().indexed().optional(),
      pos_bill_id: i.string().indexed(),
      receipt_reference: i.string().indexed().optional(),
      restaurant_id: i.string().indexed(),
      source_updated_at: i.date().indexed().optional(),
      status: i.string().indexed(),
      terminal_id: i.string().indexed().optional(),
      updated_at: i.date().indexed().optional(),
    }),
    private_event_inquiries: i.entity({
      contact_email: i.string().indexed().optional(),
      contact_name: i.string().optional(),
      created_at: i.date().indexed().optional(),
      entry_key: i.string().unique().indexed(),
      estimated_pax: i.number(),
      event_type: i.string(),
      notes: i.string().optional(),
      preferred_date: i.string().indexed(),
    }),
    private_event_types: i.entity({
      created_at: i.date().indexed().optional(),
      is_active: i.boolean().indexed().optional(),
      label_key: i.string(),
      sort_order: i.number().indexed().optional(),
      value: i.string().unique().indexed(),
    }),
    profiles: i.entity({
      auth_provider: i.string().optional(),
      avatar_url: i.string().optional(),
      bio: i.string().optional(),
      cashback_points_balance: i.number().optional(),
      cashback_points_lifetime_earned: i.number().optional(),
      created_at: i.date().indexed().optional(),
      date_of_birth: i.string().optional(),
      full_name: i.string().optional(),
      has_seen_welcome_voucher: i.boolean().optional(),
      lifetime_tier_key: i.string().optional(),
      location_permission_status: i.string().optional(),
      member_id: i.string().unique().indexed(),
      member_segment: i.string().optional(),
      member_since: i.date().indexed().optional(),
      next_tier_key: i.string().optional(),
      nights_left: i.number().optional(),
      onboarding_completed_at: i.date().indexed().optional(),
      push_notification_permission_status: i.string().optional(),
      referral_code: i.string().unique().indexed(),
      saved: i.number().optional(),
      tier_progress_expires_at: i.date().indexed().optional(),
      tier_progress_points: i.number().optional(),
      tier_progress_started_at: i.date().indexed().optional(),
      tier_progress_target_points: i.number().optional(),
      updated_at: i.date().indexed().optional(),
      userId: i.string().indexed().optional(),
    }),
    referrals: i.entity({
      created_at: i.date().indexed().optional(),
      referee_profile_id: i.string().unique().indexed().optional(),
      referred_avatar: i.string().optional(),
      referred_name: i.string().optional(),
      referrer_id: i.string().indexed().optional(),
      status: i.string().indexed().optional(),
    }),
    reviews: i.entity({
      comment: i.string().optional(),
      created_at: i.date().indexed().optional(),
      rating: i.number(),
    }),
    reward_transactions: i.entity({
      amount_vnd: i.number().indexed(),
      cashback_points_delta: i.number(),
      created_at: i.date().indexed().optional(),
      entry_key: i.string().unique().indexed(),
      event_type: i.string().indexed(),
      external_event_id: i.string().indexed(),
      member_id: i.string().indexed(),
      occurred_at: i.date().indexed().optional(),
      reference: i.string().indexed().optional(),
      source: i.string().indexed(),
      status: i.string().indexed(),
      tier_progress_points_delta: i.number(),
      updated_at: i.date().indexed().optional(),
    }),
    saved_events: i.entity({
      created_at: i.date().indexed().optional(),
      entry_key: i.string().unique().indexed(),
      event_id: i.string().indexed(),
    }),
    table_reservations: i.entity({
      contact_email: i.string().indexed(),
      created_at: i.date().indexed().optional(),
      entry_key: i.string().unique().indexed(),
      event_id: i.string().indexed().optional(),
      event_title: i.string().optional(),
      occasion: i.string().optional(),
      party_size: i.number(),
      reservation_date: i.string().indexed(),
      reservation_time: i.string().indexed(),
      source: i.string().indexed(),
      special_request: i.string().optional(),
      status: i.string().indexed(),
      updated_at: i.date().indexed().optional(),
    }),
  },
  links: {
    $streams$files: {
      forward: {
        on: '$streams',
        has: 'many',
        label: '$files',
      },
      reverse: {
        on: '$files',
        has: 'one',
        label: '$stream',
        onDelete: 'cascade',
      },
    },
    $usersLinkedPrimaryUser: {
      forward: {
        on: '$users',
        has: 'one',
        label: 'linkedPrimaryUser',
        onDelete: 'cascade',
      },
      reverse: {
        on: '$users',
        has: 'many',
        label: 'linkedGuestUsers',
      },
    },
    partner_redemptionsOwner: {
      forward: {
        on: 'partner_redemptions',
        has: 'one',
        label: 'owner',
        onDelete: 'cascade',
      },
      reverse: {
        on: '$users',
        has: 'many',
        label: 'partner_redemptions',
      },
    },
    partner_redemptionsPartner: {
      forward: {
        on: 'partner_redemptions',
        has: 'one',
        label: 'partner',
      },
      reverse: {
        on: 'partners',
        has: 'many',
        label: 'partner_redemptions',
      },
    },
    private_event_inquiriesOwner: {
      forward: {
        on: 'private_event_inquiries',
        has: 'one',
        label: 'owner',
        onDelete: 'cascade',
      },
      reverse: {
        on: '$users',
        has: 'many',
        label: 'private_event_inquiries',
      },
    },
    referralsReferrer: {
      forward: {
        on: 'referrals',
        has: 'one',
        label: 'referrer',
      },
      reverse: {
        on: 'profiles',
        has: 'many',
        label: 'referrals',
      },
    },
    reviewsOwner: {
      forward: {
        on: 'reviews',
        has: 'one',
        label: 'owner',
        onDelete: 'cascade',
      },
      reverse: {
        on: '$users',
        has: 'many',
        label: 'reviews',
      },
    },
    reward_transactionsMember: {
      forward: {
        on: 'reward_transactions',
        has: 'one',
        label: 'member',
      },
      reverse: {
        on: 'profiles',
        has: 'many',
        label: 'reward_transactions',
      },
    },
    saved_eventsEvent: {
      forward: {
        on: 'saved_events',
        has: 'one',
        label: 'event',
      },
      reverse: {
        on: 'events',
        has: 'many',
        label: 'saved_events',
      },
    },
    saved_eventsOwner: {
      forward: {
        on: 'saved_events',
        has: 'one',
        label: 'owner',
        onDelete: 'cascade',
      },
      reverse: {
        on: '$users',
        has: 'many',
        label: 'saved_events',
      },
    },
    table_reservationsEvent: {
      forward: {
        on: 'table_reservations',
        has: 'one',
        label: 'event',
      },
      reverse: {
        on: 'events',
        has: 'many',
        label: 'table_reservations',
      },
    },
    table_reservationsOwner: {
      forward: {
        on: 'table_reservations',
        has: 'one',
        label: 'owner',
        onDelete: 'cascade',
      },
      reverse: {
        on: '$users',
        has: 'many',
        label: 'table_reservations',
      },
    },
  },
  rooms: {},
});

// This helps TypeScript display nicer intellisense
type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
